services:
  fbclient:
    image: fbclient:latest
    container_name: fbclient
    platform: linux/amd64
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Asia/Shanghai"
    shm_size: "1gb"
    restart: unless-stopped
